spring:
  application:
    name: phoenix-mybatis
  datasource:
    driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
    url: "jdbc:phoenix:192.168.5.101:2181:/hbase"
    hikari:
      max-lifetime: 180000
      minimum-idle: 1
      maximum-pool-size: 2
      connection-timeout: 30000
      data-source-properties:
        phoenix:
          query:
            timeoutMs: 1200000
        hbase:
          rpc:
            timeout: 1200000
          client:
            scanner:
              timeout:
                period: 1200000

server:
  port: 80

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: "classpath*:com/phoenix/mapper/*Mapper.xml"



